- name: sleep 5 sec (override with variable wait_for_rootfs) for the aws storage to be available
  pause:
    seconds: "{{wait_for_rootfs | default(5)}}"

- name: Ensure build-essential is installed
  apt:
    name: "{{ build_essential_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: 1200
